services:
  app:
    build: .
    container_name: watchtower_bot
    # ðŸ‘‡ BU KISIM Ã‡OK Ã–NEMLÄ° ðŸ‘‡
    cap_add:
      - NET_ADMIN
    # ðŸ‘† EÄžER BU YOKSA -sS Ã‡ALIÅžMAZ ðŸ‘†
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Istanbul
    dns:
      - 8.8.8.8
      - 8.8.4.4